PE-10480 Added common authoriser
PeakBI/incubator-superset pull request #99
Opened 2021-11-02 11:46 UTC by knowvishnu

2021-11-02 12:25 UTC, sukhbir-singh commented on superset/peak/authorizer.py
> +        login_user(user, remember=False,
add condition for logging user based on boolean parameter. take parameter default as true.

2021-11-08 06:54 UTC, sukhbir-singh approved these changes

2021-11-08 07:32 UTC, abhijeet-peak approved these changes

2021-11-08 07:33 UTC, shreyashfederer approved these changes

2021-11-08 07:37 UTC, mukulsaini commented on superset/peak/authorizer.py
> +        logging.info("Successful Login!")
Successful login won't give much useful info. better to add the username also here.

2021-11-08 07:42 UTC, mukulsaini requested changes

2021-11-08 07:42 UTC, mukulsaini commented on superset/peak/decorators.py
> +            form_str = json.loads(form_data)
this can break if `form_data` is `None`, and we do `json.loads` on `None` type.

2021-11-08 08:07 UTC, sukhbir-singh commented on superset/peak/authorizer.py
> +        logging.info("Successful Login!")
resolved

2021-11-08 08:07 UTC, sukhbir-singh commented on superset/peak/decorators.py
> +            form_str = json.loads(form_data)
resolved

2021-11-08 08:42 UTC, sukhbir-singh approved these changes

2021-11-08 08:44 UTC, mukulsaini approved these changes

2021-11-08 08:44 UTC, merged